name: "Sphinx: Render docs"

on: 
  push:
    branches: [ main ]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SOURCEDIR: .
      BUILDDIR: ../docs

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies for Sphinx
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme
        python -m pip install sphinx-autoapi

    - name: make the sphinx docs
      shell: bash
      run: |
        cd docsrc
        make html

    # - name: Build HTML
    #   uses: ammaraskar/sphinx-action@master

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: html-docs
    #     path: docs/html/

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: docs/html